// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoZ7EnZdkSBE5NBkryV-r1ohj8rAx3AzI',
    appId: '1:28687002437:web:c99032828ed2ecde222c2c',
    messagingSenderId: '28687002437',
    projectId: 'emart-11a1d',
    authDomain: 'emart-11a1d.firebaseapp.com',
    storageBucket: 'emart-11a1d.firebasestorage.app',
    measurementId: 'G-YSX8828CG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJKvOv3cNP8lU6M_umGiDdZgK662_ChrI',
    appId: '1:28687002437:android:dab7a509f44e2887222c2c',
    messagingSenderId: '28687002437',
    projectId: 'emart-11a1d',
    storageBucket: 'emart-11a1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMzkAWc7TzxMvo09KItz1XJOCK7tsRCiQ',
    appId: '1:28687002437:ios:8c1a83a304442e82222c2c',
    messagingSenderId: '28687002437',
    projectId: 'emart-11a1d',
    storageBucket: 'emart-11a1d.firebasestorage.app',
    iosBundleId: 'com.example.eapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMzkAWc7TzxMvo09KItz1XJOCK7tsRCiQ',
    appId: '1:28687002437:ios:8c1a83a304442e82222c2c',
    messagingSenderId: '28687002437',
    projectId: 'emart-11a1d',
    storageBucket: 'emart-11a1d.firebasestorage.app',
    iosBundleId: 'com.example.eapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoZ7EnZdkSBE5NBkryV-r1ohj8rAx3AzI',
    appId: '1:28687002437:web:a255a452f74c29fb222c2c',
    messagingSenderId: '28687002437',
    projectId: 'emart-11a1d',
    authDomain: 'emart-11a1d.firebaseapp.com',
    storageBucket: 'emart-11a1d.firebasestorage.app',
    measurementId: 'G-6M6Q3E9RDW',
  );
}
